### ISSUE TITLE
npm 패키지 게시

### ISSUE THREAD

**Issue by hyunbinseo** [sun-typeface/SUIT#13]
안녕하세요, 제작해 주신 SUIT 글꼴 정말 잘 활용하고 있습니다.

지난달 [jsDelivr 측 인증서 문제](https://github.com/jsdelivr/jsdelivr/issues/18565)로 CDN 작동이 안 되던 문제가 있었습니다. 이로 인해 웹 폰트 호스팅도 멈췄었는데요,

이러한 문제를 원천봉쇄하고자 SUIT 글꼴을 자사 서버에서 셀프 호스팅하고자 합니다.

글꼴이 npm 패키지 형태로 배포되면 셀프 호스팅 및 버전 관리가 매우 용이해지는데,

혹시 직접 게시할 의사나 계획이 있으실지 문의드립니다.

---

예시는 [FontSource 제공 Noto Sans KR](https://fontsource.org/fonts/noto-sans-kr/install)로, 패키지 설치 후 이렇게만 적어두면 프로젝트에 글꼴이 자동 포함됩니다.

```css
@import '@fontsource-variable/noto-sans-kr';

body {
  font-family: 'Noto Sans KR Variable', sans-serif;
}
```
